import type {
  CaseDetail,
  CaseRecord,
  DataSource,
  IngestionJob,
  ModelPrediction,
  ModelVersion,
  NotificationRecord,
  NotificationTemplate,
  ReconciliationResult,
  ReconciliationSummary,
  RiskScoringDashboard,
  RiskSignal,
  RuleDefinition,
  TaxGapRanking,
  TaxGapSummary,
  TaxpayerGraph,
  TaxpayerProfile,
  UserSummary,
} from "@/lib/types";

export const demoUser: UserSummary = {
  email: "phase2-admin@example.test",
  fullName: "Phase Two Administrator",
  id: "demo-admin",
  roles: ["ADMIN"],
};

export const demoSignals: RiskSignal[] = [
  {
    confidenceScore: 94,
    createdAt: "2026-05-31T06:00:00Z",
    declaredAmount: 8400000,
    estimatedGap: 38200000,
    evidence: {
      sourceRecords: ["INV-1042", "VAT-2026-04"],
      recommendation: "Open VAT review case",
    },
    explanation: "Output VAT is materially below eTIMS invoice totals for the same period.",
    id: "signal-vat-001",
    observedAmount: 46600000,
    periodEnd: "2026-04-30",
    periodStart: "2026-04-01",
    ruleCode: "VAT_OUTPUT_MISMATCH",
    severity: "HIGH",
    signalType: "DETERMINISTIC",
    status: "OPEN",
    taxHead: "VAT",
    taxpayerId: "taxpayer-amani",
    taxpayerName: "Amani Wholesale Traders",
    taxpayerPin: "P051234567A",
  },
  {
    confidenceScore: 89,
    createdAt: "2026-05-30T12:20:00Z",
    declaredAmount: 11800000,
    estimatedGap: 27500000,
    evidence: {
      sourceRecords: ["CUS-7781", "ITR-2026-Q1"],
      recommendation: "Compare imports to sales ledger",
    },
    explanation: "Customs import value is not reflected in declared income for the quarter.",
    id: "signal-import-002",
    observedAmount: 39300000,
    periodEnd: "2026-03-31",
    periodStart: "2026-01-01",
    ruleCode: "IMPORT_TO_SALES_MISMATCH",
    severity: "HIGH",
    signalType: "DETERMINISTIC",
    status: "OPEN",
    taxHead: "INCOME_TAX",
    taxpayerId: "taxpayer-rift",
    taxpayerName: "Rift Valley Logistics Ltd",
    taxpayerPin: "P071122334B",
  },
  {
    confidenceScore: 82,
    createdAt: "2026-05-29T09:15:00Z",
    declaredAmount: 2900000,
    estimatedGap: 8100000,
    evidence: {
      sourceRecords: ["PAY-4490", "SET-1188"],
      recommendation: "Review settlement records",
    },
    explanation: "Collections exceed settlement records for the channel and date window.",
    id: "signal-settlement-003",
    observedAmount: 11000000,
    periodEnd: "2026-05-20",
    periodStart: "2026-05-01",
    ruleCode: "SETTLEMENT_VARIANCE",
    severity: "MEDIUM",
    signalType: "DETERMINISTIC",
    status: "OPEN",
    taxHead: "SETTLEMENT",
    taxpayerId: "taxpayer-kisumu",
    taxpayerName: "Kisumu County Channel 4",
    taxpayerPin: "C004556677K",
  },
];

export const demoRanking: TaxGapRanking[] = demoSignals.map((signal, index) => ({
  confidenceScore: signal.confidenceScore,
  estimatedGap: signal.estimatedGap,
  estimatedRecoverableTax: Math.round(signal.estimatedGap * (index === 1 ? 0.3 : 0.16)),
  estimatedTotalDue: Math.round(signal.estimatedGap * (index === 1 ? 1.3 : 1.16)),
  mainFactors: signal.evidence,
  periodEnd: signal.periodEnd,
  periodStart: signal.periodStart,
  score: signal.estimatedGap * (signal.confidenceScore / 100),
  taxpayerId: signal.taxpayerId ?? `demo-taxpayer-${index}`,
  taxpayerName: signal.taxpayerName ?? "Public revenue channel",
  taxpayerPin: signal.taxpayerPin ?? "No taxpayer PIN",
}));

export const demoSummary: TaxGapSummary[] = [
  {
    averageConfidence: 94,
    estimatedGap: 38200000,
    estimatedRecoverableTax: 6112000,
    signalCount: 1,
    taxHead: "VAT",
  },
  {
    averageConfidence: 89,
    estimatedGap: 27500000,
    estimatedRecoverableTax: 8250000,
    signalCount: 1,
    taxHead: "INCOME_TAX",
  },
  {
    averageConfidence: 82,
    estimatedGap: 8100000,
    estimatedRecoverableTax: 1296000,
    signalCount: 1,
    taxHead: "SETTLEMENT",
  },
];

export const demoCases: CaseRecord[] = [
  {
    agreedAmount: null,
    assessedAmount: null,
    assignedOfficerName: "Grace Njeri",
    assignedTo: "officer-grace",
    caseNumber: "CASE-20260531-001",
    caseType: "VAT",
    closedAt: null,
    closureReason: null,
    collectedAmount: null,
    estimatedRecoverableAmount: 6112000,
    id: "case-001",
    openedAt: "2026-05-31T07:10:00Z",
    priority: "HIGH",
    riskSignalId: "signal-vat-001",
    status: "IN_REVIEW",
    taxpayerId: "taxpayer-amani",
    taxpayerName: "Amani Wholesale Traders",
    taxpayerPin: "P051234567A",
    title: "VAT output mismatch for Amani Wholesale Traders",
  },
  {
    agreedAmount: 1750000,
    assessedAmount: 2200000,
    assignedOfficerName: "Daniel Otieno",
    assignedTo: "officer-daniel",
    caseNumber: "CASE-20260530-004",
    caseType: "SETTLEMENT",
    closedAt: null,
    closureReason: null,
    collectedAmount: 950000,
    estimatedRecoverableAmount: 1296000,
    id: "case-002",
    openedAt: "2026-05-30T10:45:00Z",
    priority: "MEDIUM",
    riskSignalId: "signal-settlement-003",
    status: "AWAITING_TAXPAYER",
    taxpayerId: "taxpayer-kisumu",
    taxpayerName: "Kisumu County Channel 4",
    taxpayerPin: "C004556677K",
    title: "Settlement variance for Kisumu County Channel 4",
  },
];

export const demoCaseDetail: CaseDetail = {
  detail: demoCases[0],
  events: [
    {
      caseId: "case-001",
      createdAt: "2026-05-31T07:10:00Z",
      createdBy: "demo-admin",
      createdByName: "Phase Two Administrator",
      eventType: "OPENED",
      id: "event-001",
      note: "Case opened from high-confidence VAT signal.",
    },
    {
      caseId: "case-001",
      createdAt: "2026-05-31T08:25:00Z",
      createdBy: "officer-grace",
      createdByName: "Grace Njeri",
      eventType: "NOTE",
      id: "event-002",
      note: "Requested source invoice pack and VAT return reconciliation.",
    },
  ],
  evidencePacks: [
    {
      caseId: "case-001",
      content: {
        caseNumber: "CASE-20260531-001",
        confidence: 94,
        gap: 38200000,
        period: "2026-04-01 to 2026-04-30",
        recommendation: "Open VAT review case and request eTIMS supporting invoices.",
        rule: "VAT_OUTPUT_MISMATCH",
        sourceRecords: ["INV-1042", "VAT-2026-04"],
        taxpayer: "Amani Wholesale Traders",
      },
      fileUri: "demo://evidence/CASE-20260531-001.pdf",
      generatedAt: "2026-05-31T08:30:00Z",
      generatedBy: "demo-admin",
      generatedByName: "Phase Two Administrator",
      id: "pack-001",
      status: "READY",
      version: 1,
    },
  ],
};

export const demoIngestionJobs: IngestionJob[] = [
  {
    completedAt: "2026-05-31T06:42:10Z",
    dataSourceCode: "ETIMS",
    dataSourceId: "source-etims",
    dataSourceName: "eTIMS invoices",
    errorSummary: null,
    fileName: "etims-may-demo.csv",
    id: "job-001",
    recordsInvalid: 4,
    recordsReceived: 12500,
    recordsValid: 12496,
    startedAt: "2026-05-31T06:40:00Z",
    status: "COMPLETED",
    targetTable: "invoices",
  },
  {
    completedAt: null,
    dataSourceCode: "CUSTOMS",
    dataSourceId: "source-customs",
    dataSourceName: "Customs declarations",
    errorSummary: null,
    fileName: "customs-q1-demo.csv",
    id: "job-002",
    recordsInvalid: 0,
    recordsReceived: 4300,
    recordsValid: 4300,
    startedAt: "2026-05-31T07:20:00Z",
    status: "RUNNING",
    targetTable: "customs_declarations",
  },
];

export const demoDataSources: DataSource[] = [
  {
    active: true,
    code: "ETIMS",
    id: "source-etims",
    ingestionMethod: "CSV",
    name: "eTIMS invoices",
    ownerAgency: "KRA",
    schemaVersion: "2026.05",
    sourceType: "TAX",
  },
  {
    active: true,
    code: "CUSTOMS",
    id: "source-customs",
    ingestionMethod: "CSV",
    name: "Customs declarations",
    ownerAgency: "KRA Customs",
    schemaVersion: "2026.01",
    sourceType: "CUSTOMS",
  },
];

export const demoRules: RuleDefinition[] = [
  {
    active: true,
    code: "VAT_OUTPUT_MISMATCH",
    description: "Compares VAT output declared against eTIMS invoices.",
    name: "VAT output mismatch",
    severity: "HIGH",
    taxHead: "VAT",
    thresholdJson: { minGap: 1000000, minConfidence: 75 },
  },
  {
    active: true,
    code: "IMPORT_TO_SALES_MISMATCH",
    description: "Compares import values against declared sales.",
    name: "Import to sales mismatch",
    severity: "HIGH",
    taxHead: "INCOME_TAX",
    thresholdJson: { minGap: 2000000, minConfidence: 70 },
  },
  {
    active: true,
    code: "SETTLEMENT_VARIANCE",
    description: "Flags payment collections that do not match settlement records.",
    name: "Settlement variance",
    severity: "MEDIUM",
    taxHead: "SETTLEMENT",
    thresholdJson: { maxSettlementDelayDays: 2, minGap: 500000 },
  },
];

export const demoReconciliationSummary: ReconciliationSummary = {
  delayedCount: 1,
  duplicateCount: 1,
  exceptionCount: 4,
  expectedAmount: 24100000,
  missingCount: 1,
  resultCount: 6,
  settledAmount: 19800000,
  varianceAmount: 4300000,
  wrongAccountCount: 1,
};

export const demoReconciliationResults: ReconciliationResult[] = [
  {
    collectingAgency: "Kisumu County",
    createdAt: "2026-05-31T08:00:00Z",
    evidence: {
      exceptionType: "MISSING_SETTLEMENT",
      expectedSettlementAccount: "CBK-KRA-MAIN",
      settlementDelayDays: 2,
    },
    expectedAmount: 3200000,
    expectedSettlementAccount: "CBK-KRA-MAIN",
    id: "recon-demo-001",
    maxSettlementLagDays: null,
    reconciliationDate: "2026-05-28",
    revenueChannel: "MPESA",
    riskSignalId: "signal-settlement-003",
    settledAmount: 0,
    settlementAccount: null,
    settlementCount: 0,
    settlementStatus: "MISSING_SETTLEMENT",
    transactionCount: 184,
    varianceAmount: 3200000,
  },
  {
    collectingAgency: "Nairobi City County",
    createdAt: "2026-05-31T08:10:00Z",
    evidence: {
      exceptionType: "DELAYED_SETTLEMENT",
      maxSettlementLagDays: 6,
      settlementDelayDays: 2,
    },
    expectedAmount: 8400000,
    expectedSettlementAccount: "CBK-KRA-MAIN",
    id: "recon-demo-002",
    maxSettlementLagDays: 6,
    reconciliationDate: "2026-05-27",
    revenueChannel: "BANK",
    riskSignalId: "signal-settlement-003",
    settledAmount: 8400000,
    settlementAccount: "CBK-KRA-MAIN",
    settlementCount: 1,
    settlementStatus: "DELAYED_SETTLEMENT",
    transactionCount: 92,
    varianceAmount: 0,
  },
  {
    collectingAgency: "KRA",
    createdAt: "2026-05-31T08:20:00Z",
    evidence: {
      exceptionType: "WRONG_ACCOUNT",
      expectedSettlementAccount: "CBK-KRA-MAIN",
      settlementAccount: "COMMERCIAL-BANK-123",
    },
    expectedAmount: 12500000,
    expectedSettlementAccount: "CBK-KRA-MAIN",
    id: "recon-demo-003",
    maxSettlementLagDays: 1,
    reconciliationDate: "2026-05-26",
    revenueChannel: "CARD",
    riskSignalId: "signal-settlement-003",
    settledAmount: 12500000,
    settlementAccount: "COMMERCIAL-BANK-123",
    settlementCount: 1,
    settlementStatus: "WRONG_ACCOUNT",
    transactionCount: 211,
    varianceAmount: 0,
  },
];

export const demoNotificationTemplates: NotificationTemplate[] = [
  {
    active: true,
    bodyTemplate:
      "Dear {{taxpayerName}}, KRA has noted a possible compliance variance under {{ruleCode}} for {{periodStart}} to {{periodEnd}}. Please review and correct any return differences before formal case escalation.",
    channel: "EMAIL",
    code: "SOFT_COMPLIANCE_EMAIL",
    createdAt: "2026-06-01T08:00:00Z",
    id: "template-soft-email",
    subjectTemplate: "Voluntary compliance review for {{taxpayerName}}",
    updatedAt: "2026-06-01T08:00:00Z",
  },
  {
    active: true,
    bodyTemplate:
      "KRA notice: please review {{ruleCode}} variance for {{periodStart}} to {{periodEnd}} and correct any differences voluntarily.",
    channel: "SMS",
    code: "SOFT_COMPLIANCE_SMS",
    createdAt: "2026-06-01T08:00:00Z",
    id: "template-soft-sms",
    subjectTemplate: null,
    updatedAt: "2026-06-01T08:00:00Z",
  },
  {
    active: true,
    bodyTemplate:
      "Dear {{taxpayerName}}, case {{caseNumber}} requires your response on the observed {{ruleCode}} variance. Please submit supporting documents or a correction plan.",
    channel: "EMAIL",
    code: "CASE_FOLLOW_UP_EMAIL",
    createdAt: "2026-06-01T08:00:00Z",
    id: "template-case-email",
    subjectTemplate: "KRA case follow-up {{caseNumber}}",
    updatedAt: "2026-06-01T08:00:00Z",
  },
];

export const demoNotifications: NotificationRecord[] = [
  {
    caseId: "case-001",
    channel: "EMAIL",
    createdAt: "2026-06-01T08:10:00Z",
    deliveryProvider: "LOCAL_EMAIL",
    deliveryReference: "email-demo-notification-001",
    id: "demo-notification-001",
    messageBody:
      "Dear Amani Wholesale Traders, case CASE-20260531-001 requires your response on the observed VAT_OUTPUT_MISMATCH variance. Please submit supporting documents or a correction plan.",
    recipient: "p051234567a@example.test",
    responseBody: null,
    responseStatus: null,
    riskSignalId: "signal-vat-001",
    sentAt: "2026-06-01T08:10:00Z",
    status: "SENT",
    subject: "KRA case follow-up CASE-20260531-001",
    taxpayerId: "taxpayer-amani",
    templateCode: "CASE_FOLLOW_UP_EMAIL",
    updatedAt: "2026-06-01T08:10:00Z",
  },
  {
    caseId: "case-002",
    channel: "SMS",
    createdAt: "2026-06-01T08:20:00Z",
    deliveryProvider: "LOCAL_SMS",
    deliveryReference: "sms-demo-notification-002",
    id: "demo-notification-002",
    messageBody:
      "KRA notice: please review SETTLEMENT_VARIANCE variance for 2026-05-01 to 2026-05-20 and correct any differences voluntarily.",
    recipient: "+254700000000",
    responseBody: "Settlement documents submitted for review.",
    responseStatus: "DOCUMENTS_SUBMITTED",
    riskSignalId: "signal-settlement-003",
    sentAt: "2026-06-01T08:20:00Z",
    status: "RESPONDED",
    subject: null,
    taxpayerId: "taxpayer-kisumu",
    templateCode: "SOFT_COMPLIANCE_SMS",
    updatedAt: "2026-06-01T08:40:00Z",
  },
];

export const demoModelPredictions: ModelPrediction[] = [
  {
    createdAt: "2026-06-02T05:30:00Z",
    explanation: {
      combinedScore: 91.4,
      featureContributions: {
        customsValueExceedsDeclaredIncome: 25,
        invoiceSalesExceedDeclaredSales: 35,
        peerGroupOutlierPercentile: 15,
        riskSignalGapPressure: 20,
        withholdingIncomeExceedsDeclaredIncome: 16.4,
      },
      mainContributingFeatures: [
        "invoiceSalesExceedDeclaredSales",
        "customsValueExceedsDeclaredIncome",
        "riskSignalGapPressure",
      ],
      officerReviewRequired: true,
      peerGroupPercentile: 100,
      ruleScore: 82,
    },
    id: "prediction-amani",
    kraPin: "P051234567A",
    legalName: "Amani Wholesale Traders",
    modelVersionId: "model-phase12-demo",
    predictionType: "TAXPAYER_ANOMALY",
    score: 96,
    taxpayerId: "taxpayer-amani",
  },
  {
    createdAt: "2026-06-02T05:30:00Z",
    explanation: {
      combinedScore: 83.6,
      featureContributions: {
        customsValueExceedsDeclaredIncome: 25,
        invoiceSalesExceedDeclaredSales: 18.5,
        peerGroupOutlierPercentile: 10,
        riskSignalGapPressure: 20,
        withholdingIncomeExceedsDeclaredIncome: 6.2,
      },
      mainContributingFeatures: [
        "customsValueExceedsDeclaredIncome",
        "riskSignalGapPressure",
        "invoiceSalesExceedDeclaredSales",
      ],
      officerReviewRequired: true,
      peerGroupPercentile: 67,
      ruleScore: 76,
    },
    id: "prediction-rift",
    kraPin: "P071122334B",
    legalName: "Rift Valley Logistics Ltd",
    modelVersionId: "model-phase12-demo",
    predictionType: "TAXPAYER_ANOMALY",
    score: 88,
    taxpayerId: "taxpayer-rift",
  },
  {
    createdAt: "2026-06-02T05:30:00Z",
    explanation: {
      combinedScore: 52.8,
      featureContributions: {
        customsValueExceedsDeclaredIncome: 0,
        invoiceSalesExceedDeclaredSales: 7.2,
        peerGroupOutlierPercentile: 5,
        riskSignalGapPressure: 12,
        withholdingIncomeExceedsDeclaredIncome: 0,
      },
      mainContributingFeatures: [
        "riskSignalGapPressure",
        "invoiceSalesExceedDeclaredSales",
        "peerGroupOutlierPercentile",
      ],
      officerReviewRequired: true,
      peerGroupPercentile: 33,
      ruleScore: 60,
    },
    id: "prediction-kisumu",
    kraPin: "C004556677K",
    legalName: "Kisumu County Channel 4",
    modelVersionId: "model-phase12-demo",
    predictionType: "TAXPAYER_ANOMALY",
    score: 48,
    taxpayerId: "taxpayer-kisumu",
  },
];

export const demoModelVersions: ModelVersion[] = [
  {
    active: true,
    createdAt: "2026-06-02T05:30:00Z",
    id: "model-phase12-demo",
    metrics: {
      algorithm: "ISOLATION_FOREST_WITH_PEER_PERCENTILE",
      officerReviewRequired: true,
      reproducibilitySeed: 42,
      taxpayersTrained: 3,
    },
    modelName: "PHASE12_UNSUPERVISED_RISK_SCORING",
    modelType: "UNSUPERVISED_ANOMALY",
    trainingDataSummary:
      "IsolationForest trained on 3 taxpayer observations and 7 engineered features",
    version: "phase12-demo-isolation",
  },
];

export const demoRiskScoringDashboard: RiskScoringDashboard = {
  activeModelVersion: "phase12-demo-isolation",
  averageCombinedScore: 75.93,
  averageModelScore: 78,
  highRiskCount: 2,
  predictionCount: demoModelPredictions.length,
  topPredictions: demoModelPredictions,
};

export const demoProfile: TaxpayerProfile = {
  county: "Nairobi",
  identifiers: [
    {
      confidenceScore: 99,
      identifierType: "KRA_PIN",
      identifierValue: "P051234567A",
      source: "taxpayers",
    },
    {
      confidenceScore: 91,
      identifierType: "REGISTRATION_NUMBER",
      identifierValue: "CPR/2020/1288",
      source: "business_permits",
    },
  ],
  kraPin: "P051234567A",
  legalName: "Amani Wholesale Traders",
  recordCounts: {
    businessPermits: 2,
    customsDeclarations: 8,
    invoicesAsBuyer: 54,
    invoicesAsSupplier: 118,
    paymentTransactions: 77,
    properties: 1,
    taxReturns: 5,
    withholdingAsPayee: 3,
    withholdingAsPayer: 11,
  },
  registrationNumber: "CPR/2020/1288",
  relationships: [
    {
      confidenceScore: 86,
      relatedPersonName: "Amani Directors Trust",
      relatedTaxpayerId: "taxpayer-related-001",
      relationshipType: "DIRECTOR",
      source: "business_registry",
    },
  ],
  sectorName: "Wholesale and Retail Trade",
  taxpayerId: "taxpayer-amani",
  taxpayerType: "COMPANY",
  totals: {
    buyerInvoiceTotal: 42600000,
    customsValue: 18800000,
    declaredSales: 8400000,
    payments: 28100000,
    supplierInvoiceTotal: 46600000,
  },
  tradingName: "Amani Wholesale",
};

export const demoGraph: TaxpayerGraph = {
  edges: [
    {
      createdAt: "2026-06-02T06:00:00Z",
      edgeType: "INVOICE_TRADE",
      evidence: { invoiceCount: 118, sourceTable: "invoices", totalAmount: 46600000 },
      id: "edge-demo-invoice",
      source: "ETIMS_INVOICES",
      sourceId: "taxpayer-amani",
      sourceLabel: "Amani Wholesale Traders",
      sourceType: "TAXPAYER",
      targetId: "taxpayer-related-002",
      targetLabel: "Kisumu Retail Network",
      targetType: "TAXPAYER",
      weight: 118,
    },
    {
      createdAt: "2026-06-02T06:00:00Z",
      edgeType: "PAYMENT_CHANNEL_USAGE",
      evidence: { sourceTable: "payment_transactions", totalAmount: 28100000 },
      id: "edge-demo-payment",
      source: "PAYMENT_TRANSACTIONS",
      sourceId: "taxpayer-amani",
      sourceLabel: "Amani Wholesale Traders",
      sourceType: "TAXPAYER",
      targetId: "channel-mpesa",
      targetLabel: "KRA / MPESA",
      targetType: "PAYMENT_CHANNEL",
      weight: 77,
    },
    {
      createdAt: "2026-06-02T06:00:00Z",
      edgeType: "COUNTY_PERMIT_ACTIVITY",
      evidence: { activePermitCount: 2, sourceTable: "business_permits" },
      id: "edge-demo-permit",
      source: "BUSINESS_PERMITS",
      sourceId: "taxpayer-amani",
      sourceLabel: "Amani Wholesale Traders",
      sourceType: "TAXPAYER",
      targetId: "permit-nairobi",
      targetLabel: "Nairobi permits",
      targetType: "PERMIT_COUNTY",
      weight: 2,
    },
  ],
  highRiskClusters: [
    {
      clusterKey: "demo-cluster-1",
      edgeType: "INVOICE_TRADE",
      edgeWeight: 118,
      reasons: ["Source risk score 86.00", "Invoice trade concentration"],
      sourceRiskScore: 86,
      sourceTaxpayerId: "taxpayer-amani",
      sourceTaxpayerName: "Amani Wholesale Traders",
      targetRiskScore: 74,
      targetTaxpayerId: "taxpayer-related-002",
      targetTaxpayerName: "Kisumu Retail Network",
    },
  ],
  nodes: [
    { id: "taxpayer-amani", label: "Amani Wholesale Traders", nodeType: "TAXPAYER", riskScore: 86 },
    { id: "taxpayer-related-002", label: "Kisumu Retail Network", nodeType: "TAXPAYER", riskScore: 74 },
    { id: "channel-mpesa", label: "KRA / MPESA", nodeType: "PAYMENT_CHANNEL", riskScore: 0 },
    { id: "permit-nairobi", label: "Nairobi permits", nodeType: "PERMIT_COUNTY", riskScore: 0 },
  ],
  taxpayerId: "taxpayer-amani",
};
